version: "3.3"

services:

  workstation:
    image: vulpes:latest
    build: ./vulpes
    hostname: vulpes
    environment:
      PORT: 6080
      PASSWORD: vulpes123
    ports:
      - 8001:80
      - 2222:22
      - 8083:8083 # Caido
    volumes:
      - ./Shared:/shared
      - ./vulpkg:/var/lib/vulpkg/repo
      - ./applications:/home/vulpes/.local/share/applications
      - ./icons:/home/vulpes/.local/share/icons
    cap_add:
      - NET_ADMIN
    privileged: true

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    restart: unless-stopped
#    ports:
#      - "8000:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      #- ./vulpes/settings.json:/etc/nginx/html/display/settings.json
#      #- ./vulpes/settings.json:/etc/nginx/html/settings.json
#      - ./vulpes/WebOS/:/opt/WebOS/:ro
