version: "3.3"

services:

  workstation:
    image: vulpes:latest
    build: ./vulpes
    hostname: vulpes
    environment:
      PORT: 6080
    ports:
      - 6080:6080
    volumes:
      - $HOME/Shared:/shared:ro
    cap_add:
      - NET_ADMIN
    privileged: true

  novnc:
    image: vulpes-novnc:latest
    build: ./novnc
    ports: 8000:80
