version: "3.3"

services:

  workstation:
    image: vulpes:latest
    build: ./vulpes
    hostname: vulpes
    environment:
      PORT: 6080
      PASSWORD: CHANGEME
    ports:
      - 6080:6080
      - 5900:5900
    volumes:
      - $HOME/Shared:/shared:ro
    cap_add:
      - NET_ADMIN
    privileged: true